### PR TITLE
documentation improvements

### PR DESCRIPTION
**Pull request by sdondley**
See Issue #34

### CODE REVIEW

**Review by JJ — APPROVED** [review]

**Comment by JJ** [comment]
Error is unrelated, but something we need to address anyway. I'll merge.

**Comment by sdondley** [comment]
I don't follow. Which errors are unrelated to what?

**Comment by JJ** [comment]
Check out the "Checks" tab.

**Comment by sdondley** [comment]
Oh gotcha. I thought you were referring to wrote I wrote in the documentation.

**Pull request merged**
